--------------------------------------------------------------------------------
-- Personal-trainer SaaS schema (generated by the orchestrator pipeline).
--
-- Tables: clients, coaching_notes, plan_assignments, workout_logs,
--         client_subscriptions
--
-- Auth model: trainers authenticate via Supabase Auth (auth.users).
-- Every data row carries trainer_id; RLS enforces trainer_id = auth.uid() so
-- a trainer can only see and mutate their own data. `WITH CHECK` clauses
-- on INSERT/UPDATE also prevent reassigning a row to another trainer.
--------------------------------------------------------------------------------

create extension if not exists "pgcrypto";
create extension if not exists "pg_trgm";

-- ==========================================================================
-- Enums
-- ==========================================================================

create type public.client_status as enum ('active', 'paused', 'archived');

create type public.client_subscription_status as enum (
  'trialing',
  'active',
  'past_due',
  'canceled',
  'unpaid',
  'incomplete',
  'incomplete_expired',
  'paused'
);

-- ==========================================================================
-- Shared trigger for updated_at bookkeeping
-- ==========================================================================

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ==========================================================================
-- clients
-- ==========================================================================

create table public.clients (
  id uuid primary key default gen_random_uuid(),
  trainer_id uuid not null references auth.users(id) on delete cascade,
  full_name text not null,
  email text not null,
  phone text,
  goals text,
  notes text,
  status public.client_status not null default 'active',
  invitation_token text,
  invited_at timestamptz,
  accepted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint clients_full_name_length
    check (char_length(full_name) between 1 and 255),
  constraint clients_email_length
    check (char_length(email) between 3 and 255),
  constraint clients_phone_length
    check (phone is null or char_length(phone) <= 50),
  constraint clients_goals_length
    check (goals is null or char_length(goals) <= 5000),
  constraint clients_notes_length
    check (notes is null or char_length(notes) <= 5000),
  constraint clients_trainer_email_unique
    unique (trainer_id, email)
);

create index clients_trainer_id_idx
  on public.clients (trainer_id);
create index clients_trainer_status_idx
  on public.clients (trainer_id, status);
create index clients_trainer_created_idx
  on public.clients (trainer_id, created_at desc);
create index clients_full_name_trgm_idx
  on public.clients using gin (full_name gin_trgm_ops);
create index clients_email_trgm_idx
  on public.clients using gin (email gin_trgm_ops);

create trigger clients_touch_updated_at
  before update on public.clients
  for each row execute function public.touch_updated_at();

-- ==========================================================================
-- coaching_notes (private trainer-only notes attached to a client)
-- ==========================================================================

create table public.coaching_notes (
  id uuid primary key default gen_random_uuid(),
  trainer_id uuid not null references auth.users(id) on delete cascade,
  client_id uuid not null references public.clients(id) on delete cascade,
  note text not null,
  created_at timestamptz not null default now(),
  constraint coaching_notes_note_length
    check (char_length(note) between 1 and 10000)
);

create index coaching_notes_trainer_id_idx
  on public.coaching_notes (trainer_id);
create index coaching_notes_client_id_idx
  on public.coaching_notes (client_id);
create index coaching_notes_client_created_idx
  on public.coaching_notes (client_id, created_at desc);

-- ==========================================================================
-- plan_assignments (links a client to an active workout plan)
--
-- The actual workout-plan definitions (sets/reps/exercises) live on a
-- future `workout_plans` table. This table is the join: it exists now so
-- the client-management feature can count "active plans per client" and
-- drive the stats widgets.
-- ==========================================================================

create table public.plan_assignments (
  id uuid primary key default gen_random_uuid(),
  trainer_id uuid not null references auth.users(id) on delete cascade,
  client_id uuid not null references public.clients(id) on delete cascade,
  plan_id uuid not null,
  start_date date not null default current_date,
  end_date date,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint plan_assignments_date_order
    check (end_date is null or end_date >= start_date)
);

create index plan_assignments_trainer_id_idx
  on public.plan_assignments (trainer_id);
create index plan_assignments_client_id_idx
  on public.plan_assignments (client_id);
create index plan_assignments_client_active_idx
  on public.plan_assignments (client_id, is_active);
create index plan_assignments_plan_id_idx
  on public.plan_assignments (plan_id);

create trigger plan_assignments_touch_updated_at
  before update on public.plan_assignments
  for each row execute function public.touch_updated_at();

-- ==========================================================================
-- workout_logs (lightweight per-session rollup)
--
-- One row per workout session per client. Detailed set-level logs (actual
-- weight × reps per exercise) belong to a future `workout_set_logs` table;
-- this rollup is enough for completion-rate and adherence-heatmap queries.
-- ==========================================================================

create table public.workout_logs (
  id uuid primary key default gen_random_uuid(),
  trainer_id uuid not null references auth.users(id) on delete cascade,
  client_id uuid not null references public.clients(id) on delete cascade,
  plan_assignment_id uuid references public.plan_assignments(id) on delete set null,
  workout_date date not null,
  completed boolean not null default false,
  rpe smallint,
  duration_minutes integer,
  notes text,
  created_at timestamptz not null default now(),
  constraint workout_logs_rpe_range
    check (rpe is null or rpe between 1 and 10),
  constraint workout_logs_duration_non_negative
    check (duration_minutes is null or duration_minutes >= 0),
  constraint workout_logs_notes_length
    check (notes is null or char_length(notes) <= 5000)
);

create index workout_logs_trainer_id_idx
  on public.workout_logs (trainer_id);
create index workout_logs_client_id_idx
  on public.workout_logs (client_id);
create index workout_logs_client_date_idx
  on public.workout_logs (client_id, workout_date desc);
create index workout_logs_client_completed_idx
  on public.workout_logs (client_id, completed);
create index workout_logs_plan_assignment_id_idx
  on public.workout_logs (plan_assignment_id)
  where plan_assignment_id is not null;

-- ==========================================================================
-- client_subscriptions (Stripe-backed recurring billing per client)
--
-- A client can have multiple historical subscriptions, but only rows with
-- status in ('trialing','active','past_due') count towards MRR.
-- ==========================================================================

create table public.client_subscriptions (
  id uuid primary key default gen_random_uuid(),
  trainer_id uuid not null references auth.users(id) on delete cascade,
  client_id uuid not null references public.clients(id) on delete cascade,
  stripe_customer_id text,
  stripe_subscription_id text unique,
  stripe_price_id text,
  status public.client_subscription_status not null default 'active',
  amount_cents integer,
  currency text default 'usd',
  current_period_end timestamptz,
  cancel_at_period_end boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint client_subscriptions_amount_non_negative
    check (amount_cents is null or amount_cents >= 0),
  constraint client_subscriptions_currency_iso
    check (currency is null or char_length(currency) = 3)
);

create index client_subscriptions_trainer_id_idx
  on public.client_subscriptions (trainer_id);
create index client_subscriptions_client_id_idx
  on public.client_subscriptions (client_id);
create index client_subscriptions_client_status_idx
  on public.client_subscriptions (client_id, status);
create index client_subscriptions_stripe_customer_idx
  on public.client_subscriptions (stripe_customer_id)
  where stripe_customer_id is not null;

create trigger client_subscriptions_touch_updated_at
  before update on public.client_subscriptions
  for each row execute function public.touch_updated_at();

-- ==========================================================================
-- Row Level Security
-- ==========================================================================
--
-- Every table enables RLS and installs four policies (select/insert/update/
-- delete) gated on trainer_id = auth.uid(). Writes use WITH CHECK to block
-- reassignment: a trainer cannot move a row to another trainer's account.
--
-- auth.uid() is wrapped in (select ...) so Postgres caches it once per
-- statement instead of re-invoking per row — standard Supabase RLS perf
-- practice for policies that reference auth functions.
-- ==========================================================================

alter table public.clients               enable row level security;
alter table public.coaching_notes        enable row level security;
alter table public.plan_assignments      enable row level security;
alter table public.workout_logs          enable row level security;
alter table public.client_subscriptions  enable row level security;

-- clients -------------------------------------------------------------------

create policy "clients_select_own_trainer"
  on public.clients for select
  to authenticated
  using (trainer_id = (select auth.uid()));

create policy "clients_insert_own_trainer"
  on public.clients for insert
  to authenticated
  with check (trainer_id = (select auth.uid()));

create policy "clients_update_own_trainer"
  on public.clients for update
  to authenticated
  using (trainer_id = (select auth.uid()))
  with check (trainer_id = (select auth.uid()));

create policy "clients_delete_own_trainer"
  on public.clients for delete
  to authenticated
  using (trainer_id = (select auth.uid()));

-- coaching_notes ------------------------------------------------------------

create policy "coaching_notes_select_own_trainer"
  on public.coaching_notes for select
  to authenticated
  using (trainer_id = (select auth.uid()));

create policy "coaching_notes_insert_own_trainer"
  on public.coaching_notes for insert
  to authenticated
  with check (trainer_id = (select auth.uid()));

create policy "coaching_notes_update_own_trainer"
  on public.coaching_notes for update
  to authenticated
  using (trainer_id = (select auth.uid()))
  with check (trainer_id = (select auth.uid()));

create policy "coaching_notes_delete_own_trainer"
  on public.coaching_notes for delete
  to authenticated
  using (trainer_id = (select auth.uid()));

-- plan_assignments ----------------------------------------------------------

create policy "plan_assignments_select_own_trainer"
  on public.plan_assignments for select
  to authenticated
  using (trainer_id = (select auth.uid()));

create policy "plan_assignments_insert_own_trainer"
  on public.plan_assignments for insert
  to authenticated
  with check (trainer_id = (select auth.uid()));

create policy "plan_assignments_update_own_trainer"
  on public.plan_assignments for update
  to authenticated
  using (trainer_id = (select auth.uid()))
  with check (trainer_id = (select auth.uid()));

create policy "plan_assignments_delete_own_trainer"
  on public.plan_assignments for delete
  to authenticated
  using (trainer_id = (select auth.uid()));

-- workout_logs --------------------------------------------------------------

create policy "workout_logs_select_own_trainer"
  on public.workout_logs for select
  to authenticated
  using (trainer_id = (select auth.uid()));

create policy "workout_logs_insert_own_trainer"
  on public.workout_logs for insert
  to authenticated
  with check (trainer_id = (select auth.uid()));

create policy "workout_logs_update_own_trainer"
  on public.workout_logs for update
  to authenticated
  using (trainer_id = (select auth.uid()))
  with check (trainer_id = (select auth.uid()));

create policy "workout_logs_delete_own_trainer"
  on public.workout_logs for delete
  to authenticated
  using (trainer_id = (select auth.uid()));

-- client_subscriptions ------------------------------------------------------

create policy "client_subscriptions_select_own_trainer"
  on public.client_subscriptions for select
  to authenticated
  using (trainer_id = (select auth.uid()));

create policy "client_subscriptions_insert_own_trainer"
  on public.client_subscriptions for insert
  to authenticated
  with check (trainer_id = (select auth.uid()));

create policy "client_subscriptions_update_own_trainer"
  on public.client_subscriptions for update
  to authenticated
  using (trainer_id = (select auth.uid()))
  with check (trainer_id = (select auth.uid()));

create policy "client_subscriptions_delete_own_trainer"
  on public.client_subscriptions for delete
  to authenticated
  using (trainer_id = (select auth.uid()));
